### ISSUE TITLE
Bytes: add support for serializing by extending a `Vec<u8, N>`

### ISSUE THREAD

**Issue by sosthene-nitrokey** [trussed-dev/cbor-smol#12]
I would do this by using a trait implemented for `&mut [u8]`, `heapless_bytes_v0_3::Bytes<N>`, `heapless_bytes_v0_4::Bytes<N>`, `heapless_v0_7::Vec<u8, N>`, `heapless_v0_8::Vec<u8, N>`

For example this would allow the CTAP apps to serialize directly extending the response buffer.

**Comment by sosthene-nitrokey** [comment]
There is actually already the `Writer` trait for that, but it's not implemented for heapless types or exposed in a simple function.

**Comment by robin-nitrokey** [comment]
Implemented in https://github.com/trussed-dev/cbor-smol/pull/13.
